name: Styleguide

# The directory containing the source files to parse recursively
source:
  - ./sass

# The types that the generator will scan to document comment
source_type:
  - .scss
  - .md

# The assets needed to build the docs
# You may put doc related assets here too: images, css, etc.
dependencies:
  - js

# The directory where the styleguide will be built
dest: ./styleguide-build

# The directory where the template used by the generator is placed
component_dir: ./styleguide-templates
template_dir: ./styleguide-templates
